import type { Metadata } from "next";
import "@/globals.css";

export const metadata: Metadata = {
  title: "Where Learning Happens",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <head>
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
        rel="stylesheet"
      />
    </head>
    <body className="antialiased">{children}</body>
  </html>
);

export default RootLayout;
